//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodfun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int rowid { get; set; }
        public Nullable<int> company_id { get; set; }
        public string brandname { get; set; }
        public Nullable<int> tel { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public Nullable<System.TimeSpan> opentime { get; set; }
        public Nullable<System.TimeSpan> closetime { get; set; }
        public Nullable<System.DateTime> public_holiday { get; set; }
        public string logoimage_path { get; set; }
        public string indeximage_path { get; set; }
    }
}
