//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodfun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepts
    {
        public int rowid { get; set; }
        public string corevalue_title { get; set; }
        public string corevalue_descpt { get; set; }
        public string corevalue_path { get; set; }
    }
}
